apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-tekton-app2
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/robertorodriguez98/tekton.git
    targetRevision: main
    path: manifests/imagen-docker2
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true


