apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton1-app
  namespace: argocd
spec:
  destination:
    namespace: tekton1
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/robertorodriguez98/argoCD.git
    targetRevision: main
    path: manifests/prueba2
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true


